// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-vAK9qVdSxVMBECpuoTNmG6xp6lwNqqQ',
    appId: '1:741548480853:android:a9ffb558c978ce1d45b7dc',
    messagingSenderId: '741548480853',
    projectId: 'luminous-918db',
    databaseURL: 'https://luminous-918db-default-rtdb.firebaseio.com',
    storageBucket: 'luminous-918db.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbIiq7BMDgzvUX2jRBIbwXAI46BqODNhs',
    appId: '1:741548480853:web:eff557c81412ed0d45b7dc',
    messagingSenderId: '741548480853',
    projectId: 'luminous-918db',
    authDomain: 'luminous-918db.firebaseapp.com',
    databaseURL: 'https://luminous-918db-default-rtdb.firebaseio.com',
    storageBucket: 'luminous-918db.firebasestorage.app',
    measurementId: 'G-DMMZNFKDEV',
  );
}
